if(WIN32)
    #file(GLOB BOOST_PATH "${EXTERNAL_DIR}/include/boost-*/boost/asio.hpp")
    #get_filename_component(BOOST_ROOT "${BOOST_PATH}" DIRECTORY)

    set(_programfiles "")
    foreach(v "ProgramW6432" "ProgramFiles" "ProgramFiles(x86)")
        if(DEFINED "ENV{${v}}")
            file(TO_CMAKE_PATH "$ENV{${v}}" _env_programfiles)
            list(APPEND _programfiles "${_env_programfiles}")
            unset(_env_programfiles)
        endif()
    endforeach()
    if(DEFINED "ENV{SystemDrive}")
    foreach(d "Program Files" "Program Files (x86)")
        if(EXISTS "$ENV{SystemDrive}/${d}")
        list(APPEND _programfiles "$ENV{SystemDrive}/${d}")
        endif()
    endforeach()
    endif()
    
    set(WINFSP_PATH "")

    if(_programfiles)
        list(REMOVE_DUPLICATES _programfiles)
        foreach(v ${_programfiles})
            message("path: ${v}")
            file(GLOB WINFSP_PATH "${v}/WinFsp/License.txt")
            if(WINFSP_PATH)
                message("WINFSP_PATH = ${WINFSP_PATH}")
                get_filename_component(WINFSP_PATH "${WINFSP_PATH}" DIRECTORY)
                break()
            endif()
        endforeach()
    endif()
    unset(_programfiles)

    if(WINFSP_PATH)
        message("WinFsp found at: ${WINFSP_PATH}")
        set(FUSE_INCLUDE_DIRECTORY ${WINFSP_PATH}/inc)
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(FUSE_LIBRARY ${WINFSP_PATH}/lib/winfsp-x64.lib)
        else()
            set(FUSE_LIBRARY ${WINFSP_PATH}/lib/winfsp-x86.lib)
        endif()
    else()
        message(FATAL_ERROR "WinFsp not found - is it installed?")
    endif()

else()
endif()

message("FUSE_INCLUDE_DIRECTORY = ${FUSE_INCLUDE_DIRECTORY}")
message("FUSE_LIBRARY = ${FUSE_LIBRARY}")